"""add driver active_route_id

Revision ID: f3a91c2d7e4b
Revises: 61a2bf512f86
Create Date: 2026-07-11 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3a91c2d7e4b'
down_revision = '61a2bf512f86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_route_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_driver_active_route', 'routes', ['active_route_id'], ['id']
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_driver_active_route', type_='foreignkey')
        batch_op.drop_column('active_route_id')
    # ### end Alembic commands ###
